<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TmmCjMy.App\Controller\AnimalController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TmmCjMy.App\\Controller\\AnimalController::delete()'] = ($container->privates['.service_locator.TmmCjMy'] ?? $container->load('get_ServiceLocator_TmmCjMyService'))->withContext('App\\Controller\\AnimalController::delete()', $container);
    }
}
