<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.re0ldWF.App\Controller\ApiController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.re0ldWF.App\\Controller\\ApiController::index()'] = ($container->privates['.service_locator.re0ldWF'] ?? $container->load('get_ServiceLocator_Re0ldWFService'))->withContext('App\\Controller\\ApiController::index()', $container);
    }
}
