<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGregwarCaptcha_GeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'gregwar_captcha.generator' shared service.
     *
     * @return \Gregwar\CaptchaBundle\Generator\CaptchaGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha-bundle/Generator/CaptchaGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['gregwar_captcha.generator'])) {
            return $container->services['gregwar_captcha.generator'];
        }

        return $container->services['gregwar_captcha.generator'] = new \Gregwar\CaptchaBundle\Generator\CaptchaGenerator($a, ($container->services['gregwar_captcha.captcha_builder'] ??= new \Gregwar\Captcha\CaptchaBuilder()), ($container->services['gregwar_captcha.phrase_builder'] ??= new \Gregwar\Captcha\PhraseBuilder()), ($container->services['gregwar_captcha.image_file_handler'] ?? $container->load('getGregwarCaptcha_ImageFileHandlerService')));
    }
}
