<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LocationService' shared autowired service.
     *
     * @return \App\Service\LocationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LocationService.php';

        return $container->privates['App\\Service\\LocationService'] = new \App\Service\LocationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
