<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportFactory_MailersendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.transport_factory.mailersend' shared service.
     *
     * @return \Symfony\Component\Mailer\Bridge\MailerSend\Transport\MailerSendTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer-send-mailer/Transport/MailerSendTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['mailer.transport_factory.mailersend'])) {
            return $container->privates['mailer.transport_factory.mailersend'];
        }

        return $container->privates['mailer.transport_factory.mailersend'] = new \Symfony\Component\Mailer\Bridge\MailerSend\Transport\MailerSendTransportFactory($a, ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger.mailer'] ?? $container->load('getMonolog_Logger_MailerService')));
    }
}
