<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailtrapTransportFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Mailtrap\Bridge\Transport\MailtrapTransportFactory' shared autowired service.
     *
     * @return \Mailtrap\Bridge\Transport\MailtrapTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/railsware/mailtrap-php/src/Bridge/Transport/MailtrapTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Mailtrap\\Bridge\\Transport\\MailtrapTransportFactory'])) {
            return $container->privates['Mailtrap\\Bridge\\Transport\\MailtrapTransportFactory'];
        }

        return $container->privates['Mailtrap\\Bridge\\Transport\\MailtrapTransportFactory'] = new \Mailtrap\Bridge\Transport\MailtrapTransportFactory($a, ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
