<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetAdminRoleCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SetAdminRoleCommand' shared autowired service.
     *
     * @return \App\Command\SetAdminRoleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SetAdminRoleCommand.php';

        $container->privates['App\\Command\\SetAdminRoleCommand'] = $instance = new \App\Command\SetAdminRoleCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:set-admin-role');
        $instance->setDescription('Sets a user as admin');

        return $instance;
    }
}
