<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StructureController' shared autowired service.
     *
     * @return \App\Controller\StructureController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StructureController.php';

        $container->services['App\\Controller\\StructureController'] = $instance = new \App\Controller\StructureController(($container->privates['App\\Service\\LocationService'] ?? $container->load('getLocationServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\StructureController', $container));

        return $instance;
    }
}
