<?php

namespace ContainerJLQP5hu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetAdminRoleCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SetAdminRoleCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SetAdminRoleCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:set-admin-role', [], 'Sets a user as admin', false, #[\Closure(name: 'App\\Command\\SetAdminRoleCommand')] fn (): \App\Command\SetAdminRoleCommand => ($container->privates['App\\Command\\SetAdminRoleCommand'] ?? $container->load('getSetAdminRoleCommandService')));
    }
}
