<?php

namespace ContainerJxJ9ZEe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailService' shared autowired service.
     *
     * @return \App\Service\EmailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EmailService.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }
        $b = ($container->privates['App\\Security\\EmailVerifier'] ?? $container->load('getEmailVerifierService'));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }

        return $container->privates['App\\Service\\EmailService'] = new \App\Service\EmailService($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $b);
    }
}
