<?php

namespace ContainerJxJ9ZEe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailVerifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\EmailVerifier' shared autowired service.
     *
     * @return \App\Security\EmailVerifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/EmailVerifier.php';

        $a = ($container->privates['symfonycasts.verify_email.helper'] ?? $container->load('getSymfonycasts_VerifyEmail_HelperService'));

        if (isset($container->privates['App\\Security\\EmailVerifier'])) {
            return $container->privates['App\\Security\\EmailVerifier'];
        }
        $b = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Security\\EmailVerifier'])) {
            return $container->privates['App\\Security\\EmailVerifier'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\EmailVerifier'])) {
            return $container->privates['App\\Security\\EmailVerifier'];
        }

        return $container->privates['App\\Security\\EmailVerifier'] = new \App\Security\EmailVerifier($a, $b, $c, ($container->privates['symfonycasts.reset_password.helper'] ?? $container->load('getSymfonycasts_ResetPassword_HelperService')));
    }
}
