<?php

namespace ContainerJxJ9ZEe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGregwarCaptcha_TypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'gregwar_captcha.type' shared service.
     *
     * @return \Gregwar\CaptchaBundle\Type\CaptchaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha-bundle/Type/CaptchaType.php';

        $a = ($container->services['gregwar_captcha.generator'] ?? $container->load('getGregwarCaptcha_GeneratorService'));

        if (isset($container->services['gregwar_captcha.type'])) {
            return $container->services['gregwar_captcha.type'];
        }

        return $container->services['gregwar_captcha.type'] = new \Gregwar\CaptchaBundle\Type\CaptchaType(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, ($container->services['translator'] ?? self::getTranslatorService($container)), $container->parameters['gregwar_captcha.config']);
    }
}
