<?php

namespace ContainerJxJ9ZEe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGregwarCaptcha_CaptchaBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'gregwar_captcha.captcha_builder' shared service.
     *
     * @return \Gregwar\Captcha\CaptchaBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php';

        return $container->services['gregwar_captcha.captcha_builder'] = new \Gregwar\Captcha\CaptchaBuilder();
    }
}
