<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Animal__CLASSMETADATA__' => 0,
'App__Entity__Structure__CLASSMETADATA__' => 1,
'App__Entity__User__CLASSMETADATA__' => 2,
'App__Entity__ResetPasswordRequest__CLASSMETADATA__' => 3,
'Vich__UploaderBundle__Entity__File__CLASSMETADATA__' => 4,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Animal',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AnimalRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                        'gender' => $o[3],
                        'age' => $o[4],
                        'out_department' => $o[5],
                        'highlight' => $o[6],
                        'size' => $o[7],
                        'color' => $o[8],
                        'affinity' => $o[9],
                        'adoption_status' => $o[10],
                        'breed' => $o[11],
                        'type' => $o[12],
                        'thumbnail' => $o[13],
                        'images' => $o[14],
                        'description' => $o[15],
                        'isVisible' => $o[16],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'gender' => 'gender',
                        'age' => 'age',
                        'out_department' => 'out_department',
                        'highlight' => 'highlight',
                        'size' => 'size',
                        'color' => 'color',
                        'affinity' => 'affinity',
                        'adoption_status' => 'adoption_status',
                        'breed' => 'breed',
                        'type' => 'type',
                        'thumbnail' => 'thumbnail',
                        'images' => 'images',
                        'description' => 'description',
                        'is_visible' => 'isVisible',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'gender' => 'gender',
                        'age' => 'age',
                        'out_department' => 'out_department',
                        'highlight' => 'highlight',
                        'size' => 'size',
                        'color' => 'color',
                        'affinity' => 'affinity',
                        'adoption_status' => 'adoption_status',
                        'breed' => 'breed',
                        'type' => 'type',
                        'thumbnail' => 'thumbnail',
                        'images' => 'images',
                        'description' => 'description',
                        'isVisible' => 'is_visible',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'animal',
                    ],
                ],
                'associationMappings' => [
                    [
                        'structure_id' => $o[17],
                    ],
                ],
                'idGenerator' => [
                    $o[19],
                ],
                'name' => [
                    'App\\Entity\\Animal',
                    18 => 'structure_id_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'boolean',
                    'boolean',
                    'string',
                    'string',
                    'json',
                    'string',
                    'json',
                    'string',
                    'string',
                    'json',
                    'string',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                    'gender',
                    'age',
                    'out_department',
                    'highlight',
                    'size',
                    'color',
                    'affinity',
                    'adoption_status',
                    'breed',
                    'type',
                    'thumbnail',
                    'images',
                    'description',
                    'isVisible',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'gender',
                    'age',
                    'out_department',
                    'highlight',
                    'size',
                    'color',
                    'affinity',
                    'adoption_status',
                    'breed',
                    'type',
                    'thumbnail',
                    'images',
                    'description',
                    'is_visible',
                ],
                'length' => [
                    2 => 100,
                    13 => 255,
                    15 => 255,
                ],
                'enumType' => [
                    3 => 'App\\Enum\\Gender',
                    7 => 'App\\Enum\\Size',
                    'App\\Enum\\Color',
                    10 => 'App\\Enum\\AdoptionStatus',
                    12 => 'App\\Enum\\Type',
                ],
                'nullable' => [
                    15 => true,
                    18 => false,
                ],
                'fetch' => [
                    17 => 2,
                ],
                'sourceEntity' => [
                    17 => 'App\\Entity\\Animal',
                ],
                'sourceToTargetKeyColumns' => [
                    17 => [
                        'structure_id_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    17 => [
                        'id' => 'structure_id_id',
                    ],
                ],
                'joinColumns' => [
                    17 => [
                        $o[18],
                    ],
                ],
                'joinColumnFieldNames' => [
                    17 => [
                        'structure_id_id' => 'structure_id_id',
                    ],
                ],
                'unique' => [
                    18 => false,
                ],
                'referencedColumnName' => [
                    18 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    17 => 'structure_id',
                ],
                'targetEntity' => [
                    17 => 'App\\Entity\\Structure',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Structure',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\StructureRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                        'street' => $o[3],
                        'zip_code' => $o[4],
                        'city' => $o[5],
                        'phone' => $o[6],
                        'email' => $o[7],
                        'latitude' => $o[8],
                        'longitude' => $o[9],
                        'description' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'street' => 'street',
                        'zip_code' => 'zip_code',
                        'city' => 'city',
                        'phone' => 'phone',
                        'email' => 'email',
                        'latitude' => 'latitude',
                        'longitude' => 'longitude',
                        'description' => 'description',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'street' => 'street',
                        'zip_code' => 'zip_code',
                        'city' => 'city',
                        'phone' => 'phone',
                        'email' => 'email',
                        'latitude' => 'latitude',
                        'longitude' => 'longitude',
                        'description' => 'description',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'structure',
                    ],
                ],
                'associationMappings' => [
                    [
                        'users' => $o[11],
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Structure',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'integer',
                    'string',
                    'float',
                    'float',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                    'street',
                    'zip_code',
                    'city',
                    'phone',
                    'email',
                    'latitude',
                    'longitude',
                    'description',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'street',
                    'zip_code',
                    'city',
                    'phone',
                    'email',
                    'latitude',
                    'longitude',
                    'description',
                ],
                'length' => [
                    2 => 255,
                    255,
                    5 => 255,
                    7 => 255,
                    10 => 255,
                ],
                'fetch' => [
                    11 => 2,
                ],
                'sourceEntity' => [
                    11 => 'App\\Entity\\Structure',
                ],
                'mappedBy' => [
                    11 => 'structure_id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    11 => 'users',
                ],
                'targetEntity' => [
                    11 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'email' => $o[2],
                        'password' => $o[3],
                        'name' => $o[4],
                        'surname' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'password' => 'password',
                        'name' => 'name',
                        'surname' => 'surname',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'password' => 'password',
                        'name' => 'name',
                        'surname' => 'surname',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'structure_id' => $o[6],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\User',
                    7 => 'structure_id_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'email',
                    'password',
                    'name',
                    'surname',
                ],
                'columnName' => [
                    1 => 'id',
                    'email',
                    'password',
                    'name',
                    'surname',
                ],
                'length' => [
                    2 => 255,
                    255,
                    100,
                    100,
                ],
                'unique' => [
                    2 => true,
                ],
                'fetch' => [
                    6 => 2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\User',
                ],
                'inversedBy' => [
                    6 => 'users',
                ],
                'sourceToTargetKeyColumns' => [
                    6 => [
                        'structure_id_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    6 => [
                        'id' => 'structure_id_id',
                    ],
                ],
                'joinColumns' => [
                    6 => [
                        $o[7],
                    ],
                ],
                'joinColumnFieldNames' => [
                    6 => [
                        'structure_id_id' => 'structure_id_id',
                    ],
                ],
                'referencedColumnName' => [
                    7 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'structure_id',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Structure',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\ResetPasswordRequest',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ResetPasswordRequestRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'selector' => $o[2],
                        'hashedToken' => $o[3],
                        'requestedAt' => $o[4],
                        'expiresAt' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'selector' => 'selector',
                        'hashed_token' => 'hashedToken',
                        'requested_at' => 'requestedAt',
                        'expires_at' => 'expiresAt',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'selector' => 'selector',
                        'hashedToken' => 'hashed_token',
                        'requestedAt' => 'requested_at',
                        'expiresAt' => 'expires_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'reset_password_request',
                    ],
                ],
                'associationMappings' => [
                    [
                        'user' => $o[6],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\ResetPasswordRequest',
                    7 => 'user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'datetime_immutable',
                    'datetime_immutable',
                ],
                'fieldName' => [
                    1 => 'id',
                    'selector',
                    'hashedToken',
                    'requestedAt',
                    'expiresAt',
                ],
                'columnName' => [
                    1 => 'id',
                    'selector',
                    'hashed_token',
                    'requested_at',
                    'expires_at',
                ],
                'length' => [
                    2 => 20,
                    100,
                ],
                'fetch' => [
                    6 => 2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\ResetPasswordRequest',
                ],
                'sourceToTargetKeyColumns' => [
                    6 => [
                        'user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    6 => [
                        'id' => 'user_id',
                    ],
                ],
                'joinColumns' => [
                    6 => [
                        $o[7],
                    ],
                ],
                'joinColumnFieldNames' => [
                    6 => [
                        'user_id' => 'user_id',
                    ],
                ],
                'unique' => [
                    7 => false,
                ],
                'nullable' => [
                    7 => false,
                ],
                'referencedColumnName' => [
                    7 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'user',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'Vich\\UploaderBundle\\Entity',
                ],
                'rootEntityName' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'isEmbeddedClass' => [
                    true,
                ],
                'fieldMappings' => [
                    [
                        'name' => $o[1],
                        'originalName' => $o[2],
                        'mimeType' => $o[3],
                        'size' => $o[4],
                        'dimensions' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'name' => 'name',
                        'original_name' => 'originalName',
                        'mime_type' => 'mimeType',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'columnNames' => [
                    [
                        'name' => 'name',
                        'originalName' => 'original_name',
                        'mimeType' => 'mime_type',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'file',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'nullable' => [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'string',
                    'integer',
                    'simple_array',
                ],
                'fieldName' => [
                    1 => 'name',
                    'originalName',
                    'mimeType',
                    'size',
                    'dimensions',
                ],
                'columnName' => [
                    1 => 'name',
                    'original_name',
                    'mime_type',
                    'size',
                    'dimensions',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
