<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4eM6tOx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4eM6tOx/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4eM6tOx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4eM6tOx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4eM6tOx\App_KernelProdContainer([
    'container.build_hash' => '4eM6tOx',
    'container.build_id' => 'e6c5cbdb',
    'container.build_time' => 1744638842,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4eM6tOx');
