<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ResetPasswordRequest extends \App\Entity\ResetPasswordRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'expiresAt' => [parent::class, 'expiresAt', null, 8],
        "\0".'*'."\0".'hashedToken' => [parent::class, 'hashedToken', null, 8],
        "\0".'*'."\0".'requestedAt' => [parent::class, 'requestedAt', null, 8],
        "\0".'*'."\0".'selector' => [parent::class, 'selector', null, 8],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 8],
        'hashedToken' => [parent::class, 'hashedToken', null, 8],
        'id' => [parent::class, 'id', null, 16],
        'requestedAt' => [parent::class, 'requestedAt', null, 8],
        'selector' => [parent::class, 'selector', null, 8],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
