<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animal extends \App\Entity\Animal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adoption_status' => [parent::class, 'adoption_status', null, 16],
        "\0".parent::class."\0".'affinity' => [parent::class, 'affinity', null, 16],
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'breed' => [parent::class, 'breed', null, 16],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'highlight' => [parent::class, 'highlight', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null, 16],
        "\0".parent::class."\0".'isVisible' => [parent::class, 'isVisible', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'out_department' => [parent::class, 'out_department', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'structure_id' => [parent::class, 'structure_id', null, 16],
        "\0".parent::class."\0".'thumbnail' => [parent::class, 'thumbnail', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'adoption_status' => [parent::class, 'adoption_status', null, 16],
        'affinity' => [parent::class, 'affinity', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'breed' => [parent::class, 'breed', null, 16],
        'color' => [parent::class, 'color', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'highlight' => [parent::class, 'highlight', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'images' => [parent::class, 'images', null, 16],
        'isVisible' => [parent::class, 'isVisible', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'out_department' => [parent::class, 'out_department', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'structure_id' => [parent::class, 'structure_id', null, 16],
        'thumbnail' => [parent::class, 'thumbnail', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
