login_page:
    path: /
    controller: App\Controller\SecurityController::index
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  prefix: /backoffice