<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLQP5hu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLQP5hu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJLQP5hu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJLQP5hu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJLQP5hu\App_KernelDevDebugContainer([
    'container.build_hash' => 'JLQP5hu',
    'container.build_id' => 'c51647df',
    'container.build_time' => 1756640807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJLQP5hu');
