<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRi8wZhR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRi8wZhR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRi8wZhR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRi8wZhR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRi8wZhR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ri8wZhR',
    'container.build_id' => '55b92339',
    'container.build_time' => 1756643951,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRi8wZhR');
