<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerRi8wZhR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRi8wZhR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRi8wZhR.legacy');
=======
if (\class_exists(\ContainerJLQP5hu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLQP5hu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJLQP5hu.legacy');
>>>>>>> preprod

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerRi8wZhR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRi8wZhR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ri8wZhR',
    'container.build_id' => '55b92339',
    'container.build_time' => 1756643951,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRi8wZhR');
=======
    \class_alias(\ContainerJLQP5hu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJLQP5hu\App_KernelDevDebugContainer([
    'container.build_hash' => 'JLQP5hu',
    'container.build_id' => 'c51647df',
    'container.build_time' => 1756640807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJLQP5hu');
>>>>>>> preprod
