<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Tailwind_Command_Build_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.tailwind.command.build.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.tailwind.command.build.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('tailwind:build', [], 'Builds the Tailwind CSS assets.', false, #[\Closure(name: 'tailwind.command.build', class: 'Symfonycasts\\TailwindBundle\\Command\\TailwindBuildCommand')] fn (): \Symfonycasts\TailwindBundle\Command\TailwindBuildCommand => ($container->privates['tailwind.command.build'] ?? $container->load('getTailwind_Command_BuildService')));
    }
}
