<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\AnimalCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\AnimalCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\AnimalCrudController'] = $instance = new \App\Controller\Admin\AnimalCrudController();

        $instance->setContainer(($container->privates['.service_locator.5PWTx9U'] ?? $container->load('get_ServiceLocator_5PWTx9UService'))->withContext('App\\Controller\\Admin\\AnimalCrudController', $container));

        return $instance;
    }
}
