<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.p9BzBQX.App\Controller\AnimalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p9BzBQX.App\\Controller\\AnimalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animal' => ['privates', '.errored..service_locator.p9BzBQX.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.p9BzBQX": it needs an instance of "App\\Entity\\Animal" but this type has been excluded in "config/services.yaml".'],
        ], [
            'animal' => 'App\\Entity\\Animal',
        ]))->withContext('App\\Controller\\AnimalController::show()', $container);
    }
}
