<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurableDirectoryNamerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer' shared service.
     *
     * @return \Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Vich\\UploaderBundle\\Naming\\ConfigurableDirectoryNamer'] = new \Vich\UploaderBundle\Naming\ConfigurableDirectoryNamer();
    }
}
