<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordControllerresetService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qHpfPrp.App\Controller\ResetPasswordController::reset()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'passwordHasher' => '?',
            'translator' => '?',
        ]))->withContext('App\\Controller\\ResetPasswordController::reset()', $container);
    }
}
