<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureCrudControllerconfigureResponseParametersService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ib1WIGE.App\Controller\Admin\StructureCrudController::configureResponseParameters()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ib1WIGE.App\\Controller\\Admin\\StructureCrudController::configureResponseParameters()'] = ($container->privates['.service_locator.ib1WIGE'] ?? $container->load('get_ServiceLocator_Ib1WIGEService'))->withContext('App\\Controller\\Admin\\StructureCrudController::configureResponseParameters()', $container);
    }
}
