<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StructureRepository' shared autowired service.
     *
     * @return \App\Repository\StructureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StructureRepository'] = new \App\Repository\StructureRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
