<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\StructureCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\StructureCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\StructureCrudController'] = $instance = new \App\Controller\Admin\StructureCrudController();

        $instance->setContainer(($container->privates['.service_locator.5PWTx9U'] ?? $container->load('get_ServiceLocator_5PWTx9UService'))->withContext('App\\Controller\\Admin\\StructureCrudController', $container));

        return $instance;
    }
}
