<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTailwind_Command_BuildService extends App_KernelProdContainer
{
    /*
     * Gets the private 'tailwind.command.build' shared service.
     *
     * @return \Symfonycasts\TailwindBundle\Command\TailwindBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['tailwind.command.build'] = $instance = new \Symfonycasts\TailwindBundle\Command\TailwindBuildCommand(($container->privates['tailwind.builder'] ?? $container->load('getTailwind_BuilderService')));

        $instance->setName('tailwind:build');
        $instance->setDescription('Builds the Tailwind CSS assets.');

        return $instance;
    }
}
