<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTailwind_CssAssetCompilerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'tailwind.css_asset_compiler' shared service.
     *
     * @return \Symfonycasts\TailwindBundle\AssetMapper\TailwindCssAssetCompiler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tailwind.css_asset_compiler'] = new \Symfonycasts\TailwindBundle\AssetMapper\TailwindCssAssetCompiler(($container->privates['tailwind.builder'] ?? $container->load('getTailwind_BuilderService')), true);
    }
}
