<?php

namespace Container4eM6tOx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerconfigureCrudService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.OoSfY9L.App\Controller\Admin\UserCrudController::configureCrud()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OoSfY9L.App\\Controller\\Admin\\UserCrudController::configureCrud()'] = ($container->privates['.service_locator.OoSfY9L'] ?? $container->load('get_ServiceLocator_OoSfY9LService'))->withContext('App\\Controller\\Admin\\UserCrudController::configureCrud()', $container);
    }
}
