name: deploy
on:
  push:
    branches: [ preprod ]
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back  # ← Définit le répertoire par défaut
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:2.2
    - name: Create temporary .env for build
      run: |
        echo "APP_ENV=prod" > .env
        echo "GEOLOCATION_URL=https://api-adresse.data.gouv.fr" >> .env
        echo "MAILER_WEB_URL=https://example.com" >> .env
        echo "MAILER_DSN=\"smtp://127.0.0.1:1025\"" >> .env
        echo "APP_SECRET=dummy-secret-for-ci-only-$(date +%s)" >> .env
        echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/fake.db" >> .env
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: .back/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('back/composer.lock') }}
        
    - name: Install Dependencies
      run: composer install
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      working-directory: ./front
      run: npm install
      
    - name: Build Assets
      working-directory: ./front
      run: npm run build